const speed = 80

input.onButtonPressed(Button.B, function () {
    basic.clearScreen()
    basic.showString("!!WAKEUP!!")
    basic.clearScreen()
})
input.onGesture(Gesture.Shake, function () {
    for (let a = 0; a <= 4; a++) {
        led.plot(0, 0)
        basic.pause(speed)
        led.plot(1, 0)
        led.plotBrightness(1, 0, 200)
        basic.pause(speed)
        led.plot(2, 0)
        led.plotBrightness(2, 0, 70)
        basic.pause(speed)
        led.plot(3, 0)
        led.plotBrightness(3, 0, 20)
        basic.pause(speed)
        led.plot(4, 0)
        led.plotBrightness(4, 0, 3)
        basic.pause(speed)

        //line2
        led.plot(4, 1)
        basic.pause(speed)
        led.plot(3, 1)
        led.plotBrightness(3, 1, 200)
        basic.pause(speed)
        led.plot(2, 1)
        led.plotBrightness(2, 1, 70)
        basic.pause(speed)
        led.plot(1, 1)
        led.plotBrightness(1, 1, 20)
        basic.pause(speed)
        led.plot(0, 1)
        led.plotBrightness(0, 1, 3)
        basic.pause(speed)

        //line3
        led.plot(0, 2)
        basic.pause(speed)
        led.plot(1, 2)
        led.plotBrightness(1, 2, 200)
        basic.pause(speed)
        led.plot(2, 2)
        led.plotBrightness(2, 2, 70)
        basic.pause(speed)
        led.plot(3, 2)
        led.plotBrightness(3, 2, 20)
        basic.pause(speed)
        led.plot(4, 2)
        led.plotBrightness(4, 2, 3)
        basic.pause(speed)

        //line4
        led.plot(4, 3)
        basic.pause(speed)
        led.plot(3, 3)
        led.plotBrightness(3, 3, 200)
        basic.pause(speed)
        led.plot(2, 3)
        led.plotBrightness(2, 3, 70)
        basic.pause(speed)
        led.plot(1, 3)
        led.plotBrightness(1, 3, 20)
        basic.pause(speed)
        led.plot(0, 3)
        led.plotBrightness(0, 3, 3)
        basic.pause(speed)

        //line5
        led.plot(0, 4)
        basic.pause(speed)
        led.plot(1, 4)
        led.plotBrightness(1, 4, 200)
        basic.pause(speed)
        led.plot(2, 4)
        led.plotBrightness(2, 4, 70)
        basic.pause(speed)
        led.plot(3, 4)
        led.plotBrightness(3, 4, 20)
        basic.pause(speed)
        led.plot(4, 4)
        led.plotBrightness(4, 4, 3)
        basic.pause(speed)

        //reversing
        led.unplot(4, 4)
        basic.pause(speed)
        led.unplot(3, 4)
        basic.pause(speed)
        led.unplot(2, 4)
        basic.pause(speed)
        led.unplot(1, 4)
        basic.pause(speed)
        led.unplot(0, 4)
        basic.pause(speed)

        //line2
        led.unplot(0, 3)
        basic.pause(speed)
        led.unplot(1, 3)
        basic.pause(speed)
        led.unplot(2, 3)
        basic.pause(speed)
        led.unplot(3, 3)
        basic.pause(speed)
        led.unplot(4, 3)
        basic.pause(speed)

        //line3
        led.unplot(4, 2)
        basic.pause(speed)
        led.unplot(3, 2)
        basic.pause(speed)
        led.unplot(2, 2)
        basic.pause(speed)
        led.unplot(1, 2)
        basic.pause(speed)
        led.unplot(0, 2)
        basic.pause(speed)

        //line4
        led.unplot(0, 1)
        basic.pause(speed)
        led.unplot(1, 1)
        basic.pause(speed)
        led.unplot(2, 1)
        basic.pause(speed)
        led.unplot(3, 1)
        basic.pause(speed)
        led.unplot(4, 1)
        basic.pause(speed)

        //line5
        led.unplot(4, 0)
        basic.pause(speed)
        led.unplot(3, 0)
        basic.pause(speed)
        led.unplot(2, 0)
        basic.pause(speed)
        led.unplot(1, 0)
        basic.pause(speed)
        led.unplot(0, 0)
        basic.pause(speed)
    }
})
input.onGesture(Gesture.TiltRight, function () {
    for (let j = 0; j <= 4; j++) {
        led.plotAll()
        //breaking it down
        led.unplot(0, 0)
        basic.pause(speed)
        led.unplot(0, 4)
        basic.pause(speed)
        led.unplot(1, 1)
        basic.pause(speed)
        led.unplot(1, 3)
        basic.pause(speed)
        led.unplot(2, 0)
        basic.pause(speed)
        led.unplot(2, 4)
        basic.pause(speed)
        led.unplot(3, 1)
        basic.pause(speed)
        led.unplot(3, 3)
        basic.pause(speed)
        led.unplot(4, 0)
        basic.pause(speed)
        led.unplot(4, 4)
        basic.pause(speed)
        led.unplot(0, 2)
        basic.pause(speed)
        led.unplot(4, 2)
        basic.pause(speed)
        led.unplot(2, 2)
        basic.pause(400)
    }
    basic.clearScreen()
})
input.onButtonPressed(Button.A, function () {
    for (let b = 0; b <= 4; b++) {
        led.plot(4, 0)
        basic.pause(speed)
        led.plot(4, 1)
        led.plotBrightness(4, 1, 200)
        basic.pause(speed)
        led.plot(4, 2)
        led.plotBrightness(4, 2, 70)
        basic.pause(speed)
        led.plot(4, 3)
        led.plotBrightness(4, 3, 20)
        basic.pause(speed)
        led.plot(4, 4)
        led.plotBrightness(4, 4, 3)
        basic.pause(speed)

        //line2
        led.plot(3, 4)
        basic.pause(speed)
        led.plot(3, 3)
        led.plotBrightness(3, 3, 200)
        basic.pause(speed)
        led.plot(3, 2)
        led.plotBrightness(3, 2, 70)
        basic.pause(speed)
        led.plot(3, 1)
        led.plotBrightness(3, 1, 20)
        basic.pause(speed)
        led.plot(3, 0)
        led.plotBrightness(3, 0, 3)

        //line 3
        led.plot(2, 0)
        basic.pause(speed)
        led.plot(2, 1)
        led.plotBrightness(2, 1, 200)
        basic.pause(speed)
        led.plot(2, 2)
        led.plotBrightness(2, 2, 70)
        basic.pause(speed)
        led.plot(2, 3)
        led.plotBrightness(2, 3, 20)
        basic.pause(speed)
        led.plot(2, 4)
        led.plotBrightness(2, 4, 3)
        basic.pause(speed)

        //line4
        led.plot(1, 4)
        basic.pause(speed)
        led.plot(1, 3)
        led.plotBrightness(1, 3, 200)
        basic.pause(speed)
        led.plot(1, 2)
        led.plotBrightness(1, 2, 70)
        basic.pause(speed)
        led.plot(1, 1)
        led.plotBrightness(1, 1, 20)
        basic.pause(speed)
        led.plot(1, 0)
        led.plotBrightness(1, 0, 3)

        //line4

        led.plot(0, 0)
        basic.pause(speed)
        led.plot(0, 1)
        led.plotBrightness(0, 1, 200)
        basic.pause(speed)
        led.plot(0, 2)
        led.plotBrightness(0, 2, 70)
        basic.pause(speed)
        led.plot(0, 3)
        led.plotBrightness(0, 3, 20)
        basic.pause(speed)
        led.plot(0, 4)
        led.plotBrightness(0, 4, 3)
        basic.pause(speed)

        //reverse

        led.plot(0, 4)
        basic.pause(speed)
        led.plot(0, 3)
        led.plotBrightness(0, 3, 200)
        basic.pause(speed)
        led.plot(0, 2)
        led.plotBrightness(0, 2, 70)
        basic.pause(speed)
        led.plot(0, 1)
        led.plotBrightness(0, 1, 20)
        basic.pause(speed)
        led.plot(0, 0)
        led.plotBrightness(0, 0, 3)
        basic.pause(speed)

        //reverse line2

        led.plot(1, 0)
        basic.pause(speed)
        led.plot(1, 1)
        led.plotBrightness(1, 1, 200)
        basic.pause(speed)
        led.plot(1, 2)
        led.plotBrightness(1, 2, 70)
        basic.pause(speed)
        led.plot(1, 3)
        led.plotBrightness(1, 3, 20)
        basic.pause(speed)
        led.plot(1, 4)
        led.plotBrightness(1, 4, 3)

        //reverseline3

        led.plot(2, 4)
        basic.pause(speed)
        led.plot(2, 3)
        led.plotBrightness(2, 3, 200)
        basic.pause(speed)
        led.plot(2, 2)
        led.plotBrightness(2, 2, 70)
        basic.pause(speed)
        led.plot(2, 1)
        led.plotBrightness(2, 1, 20)
        basic.pause(speed)
        led.plot(2, 0)
        led.plotBrightness(2, 0, 3)
        basic.pause(speed)

        //reverse line4

        led.plot(3, 0)
        basic.pause(speed)
        led.plot(3, 1)
        led.plotBrightness(3, 1, 200)
        basic.pause(speed)
        led.plot(3, 2)
        led.plotBrightness(3, 2, 70)
        basic.pause(speed)
        led.plot(3, 3)
        led.plotBrightness(3, 3, 20)
        basic.pause(speed)
        led.plot(3, 4)
        led.plotBrightness(3, 4, 3)

        //reverse line5
        led.plot(4, 4)
        basic.pause(speed)
        led.plot(4, 3)
        led.plotBrightness(4, 3, 200)
        basic.pause(speed)
        led.plot(4, 2)
        led.plotBrightness(4, 2, 70)
        basic.pause(speed)
        led.plot(4, 1)
        led.plotBrightness(4, 1, 20)
        basic.pause(speed)
        led.plot(4, 0)
        led.plotBrightness(4, 0, 3)
        basic.pause(speed)

    }
    basic.clearScreen()
})
input.onGesture(Gesture.ScreenDown, function () {

    for (let i = 0; i <= 4; i++) {
        //setting it up
        led.plot(0, 0)
        basic.pause(speed)
        led.plot(0, 4)
        basic.pause(speed)
        led.plot(1, 1)
        basic.pause(speed)
        led.plot(1, 3)
        basic.pause(speed)
        led.plot(2, 0)
        basic.pause(speed)
        led.plot(2, 4)
        basic.pause(speed)
        led.plot(3, 1)
        basic.pause(speed)
        led.plot(3, 3)
        basic.pause(speed)
        led.plot(4, 0)
        basic.pause(speed)
        led.plot(4, 4)
        basic.pause(speed)
        led.plot(2, 2)
        basic.pause(400)

        //breaking it down
        led.unplot(0, 0)
        basic.pause(speed)
        led.unplot(0, 4)
        basic.pause(speed)
        led.unplot(1, 1)
        basic.pause(speed)
        led.unplot(1, 3)
        basic.pause(speed)
        led.unplot(2, 0)
        basic.pause(speed)
        led.unplot(2, 4)
        basic.pause(speed)
        led.unplot(3, 1)
        basic.pause(speed)
        led.unplot(3, 3)
        basic.pause(speed)
        led.unplot(4, 0)
        basic.pause(speed)
        led.unplot(4, 4)
        basic.pause(speed)
        led.unplot(2, 2)
        basic.pause(400)
    }
    basic.clearScreen()
})

input.onGesture(Gesture.TiltLeft, function () {
    for (let e = 0; e <= 4; e++) {
        led.plot(0, 0)
        basic.pause(speed)
        led.plot(1, 0)
        basic.pause(speed)
        led.plot(2, 0)
        basic.pause(speed)
        led.plot(3, 0)
        basic.pause(speed)
        led.plot(4, 0)
        basic.pause(speed)
        led.unplot(0, 0)
        basic.pause(speed)
        led.unplot(1, 0)
        basic.pause(speed)
        led.unplot(3, 0)
        basic.pause(speed)
        led.unplot(4, 0)
        basic.pause(speed)

        //line2
        led.plot(4, 1)
        basic.pause(speed)
        led.plot(3, 1)
        basic.pause(speed)
        led.plot(2, 1)
        basic.pause(speed)
        led.plot(1, 1)
        basic.pause(speed)
        led.plot(0, 1)
        basic.pause(speed)
        led.unplot(4, 1)
        basic.pause(speed)
        led.unplot(0, 1)
        basic.pause(speed)

        //line3
        led.plot(0, 2)
        basic.pause(speed)
        led.plot(1, 2)
        basic.pause(speed)
        led.plot(2, 2)
        basic.pause(speed)
        led.plot(3, 2)
        basic.pause(speed)
        led.plot(4, 2)
        basic.pause(speed)

        //line4
        led.plot(4, 3)
        basic.pause(speed)
        led.plot(3, 3)
        basic.pause(speed)
        led.plot(2, 3)
        basic.pause(speed)
        led.plot(1, 3)
        basic.pause(speed)
        led.plot(0, 3)
        basic.pause(speed)
        led.unplot(4, 3)
        basic.pause(speed)
        led.unplot(3, 3)
        basic.pause(speed)
        led.unplot(1, 3)
        basic.pause(speed)
        led.unplot(0, 3)
        basic.pause(speed)

        //line5

        led.plot(0, 4)
        basic.pause(speed)
        led.plot(1, 4)
        basic.pause(speed)
        led.plot(2, 4)
        basic.pause(speed)
        led.plot(3, 4)
        basic.pause(speed)
        led.plot(4, 4)
        basic.pause(speed)
        led.unplot(0, 4)
        basic.pause(speed)
        led.unplot(1, 4)
        basic.pause(speed)
        led.unplot(3, 4)
        basic.pause(speed)
        led.unplot(4, 4)
        basic.pause(speed)

        basic.clearScreen()
    }
})